[project]
name    = "z42.io"
version = "0.1.0"
kind    = "lib"

[dependencies]
"z42.core"     = "0.1.0"
"z42.encoding" = "0.1.0"   # Std.IO.StreamReader/Writer takes a Std.Encoding.Encoding
"z42.text"     = "0.1.0"   # Std.IO.StringWriter uses Std.Text.StringBuilder
